### ISSUE TITLE
Install packages required on debian-12-minimal base template via securedrop-workstation-config dependencies

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop-client#1956]
Currently the following Salt is used to install requirements not present in `debian-12-minimal`:

```
sd-base-template-install-additional-packages:                                   
  pkg.installed:                                                                
    - pkgs:                                                                     
      - qubes-core-agent-passwordless-root                                      
      - rsyslog                                                                 
      - mailcap                                                                 
      - apparmor                                                                
      - apparmor-utils     
``` 

Since they are required for all appVMs, we could install them via the securedrop-workstation-config package instead.
